spring.application.name=stockTracking
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/minsql
spring.datasource.username=min
spring.datasource.password=qwe123!@#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=qwe123!@#

# Kafka ?? ?? (Kafka ???? ??)
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Producer ??
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Kafka Consumer ??
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
